#!/bin/bash

g++ -o pat-tools pat-tools.cpp

sudo cp ~/pat-tools/pat-tools /usr/local/bin

[ ! -d "/usr/local/bin/lists" ] && sudo mkdir /usr/local/bin/lists

sudo find /usr/local/bin/lists -type d -exec chmod 755 {} \;

sudo chmod 777 /usr/local/bin/lists

echo "Done"
